/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IPriceSubmitterContract
  extends Truffle.Contract<IPriceSubmitterInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IPriceSubmitterInstance>;
}

export interface PriceHashesSubmitted {
  name: "PriceHashesSubmitted";
  args: {
    submitter: string;
    epochId: BN;
    ftsos: string[];
    hashes: string[];
    timestamp: BN;
    0: string;
    1: BN;
    2: string[];
    3: string[];
    4: BN;
  };
}

export interface PricesRevealed {
  name: "PricesRevealed";
  args: {
    voter: string;
    epochId: BN;
    ftsos: string[];
    prices: BN[];
    randoms: BN[];
    timestamp: BN;
    0: string;
    1: BN;
    2: string[];
    3: BN[];
    4: BN[];
    5: BN;
  };
}

type AllEvents = PriceHashesSubmitted | PricesRevealed;

export interface IPriceSubmitterInstance extends Truffle.ContractInstance {
  getFtsoManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getFtsoRegistry(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getVoterWhitelister(txDetails?: Truffle.TransactionDetails): Promise<string>;

  revealPrices: {
    (
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _prices: (number | BN | string)[],
      _randoms: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _prices: (number | BN | string)[],
      _randoms: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _prices: (number | BN | string)[],
      _randoms: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _prices: (number | BN | string)[],
      _randoms: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  submitPriceHashes: {
    (
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _hashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _hashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _hashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _epochId: number | BN | string,
      _ftsoIndices: (number | BN | string)[],
      _hashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  voterWhitelistBitmap(
    _voter: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    getFtsoManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getFtsoRegistry(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getVoterWhitelister(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    revealPrices: {
      (
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _prices: (number | BN | string)[],
        _randoms: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _prices: (number | BN | string)[],
        _randoms: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _prices: (number | BN | string)[],
        _randoms: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _prices: (number | BN | string)[],
        _randoms: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    submitPriceHashes: {
      (
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _hashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _hashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _hashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _epochId: number | BN | string,
        _ftsoIndices: (number | BN | string)[],
        _hashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    voterWhitelistBitmap(
      _voter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
